"""generating mysql migrate

Revision ID: 75055e3a550d
Revises: 
Create Date: 2026-05-06 17:06:53.161975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75055e3a550d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_users'))
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('media_type', sa.Enum('NONE', 'PHOTO', 'VIDEO', 'ANIMATION', name='admediatype'), nullable=False),
    sa.Column('media_file_id', sa.String(length=256), nullable=True),
    sa.Column('cache_channel_message_id', sa.BigInteger(), nullable=True),
    sa.Column('button_text', sa.String(length=64), nullable=True),
    sa.Column('button_url', sa.String(length=512), nullable=True),
    sa.Column('buttons', sa.JSON(), nullable=True),
    sa.Column('subscription_channel_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('subscription_channel_username', sa.String(length=128), nullable=True),
    sa.Column('subscription_channel_title', sa.String(length=256), nullable=True),
    sa.Column('subscriber_goal', sa.Integer(), nullable=True),
    sa.Column('subscribers_gained', sa.Integer(), nullable=False),
    sa.Column('target_language', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'SENDING', 'COMPLETED', 'CANCELLED', name='adstatus'), nullable=False),
    sa.Column('ad_type', sa.Enum('BROADCAST', 'POST_DOWNLOAD', 'SUBSCRIPTION_GATE', name='adtype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('auto_delete_seconds', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_recipients', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ads'))
    )
    op.create_index(op.f('ix_ads_ad_uuid'), 'ads', ['ad_uuid'], unique=True)
    op.create_index(op.f('ix_ads_expires_at'), 'ads', ['expires_at'], unique=False)
    op.create_index(op.f('ix_ads_target_language'), 'ads', ['target_language'], unique=False)
    op.create_table('bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('bot_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BANNED', name='botstatus'), nullable=False),
    sa.Column('is_webhook', sa.Boolean(), nullable=False),
    sa.Column('webhook_url', sa.String(length=512), nullable=True),
    sa.Column('webhook_secret', sa.String(length=64), nullable=True),
    sa.Column('total_users', sa.Integer(), nullable=False),
    sa.Column('active_users', sa.Integer(), nullable=False),
    sa.Column('total_downloads', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bots')),
    sa.UniqueConstraint('username', name=op.f('uq_bots_username'))
    )
    op.create_index(op.f('ix_bots_bot_id'), 'bots', ['bot_id'], unique=True)
    op.create_index(op.f('ix_bots_token'), 'bots', ['token'], unique=True)
    op.create_table('cache_channels',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Человекочитаемое название канала'),
    sa.Column('username', sa.String(length=255), nullable=True, comment='Username канала без символа @'),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False, comment='Числовой Telegram ID канала'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание или заметки о канале'),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False, comment='Используется ли канал для кэширования'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='Когда в последний раз использовали этот канал для загрузки'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cache_channels')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_cache_channels_telegram_id')),
    sa.UniqueConstraint('username', name=op.f('uq_cache_channels_username'))
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('INSTAGRAM', 'TIKTOK', 'YOUTUBE', 'PINTEREST', 'TWITTER', 'REDDIT', 'OTHER', name='mediasource'), nullable=False),
    sa.Column('platform_icon', sa.String(length=50), nullable=True),
    sa.Column('original_url', sa.String(length=512), nullable=False),
    sa.Column('original_id', sa.String(length=256), nullable=True),
    sa.Column('telegram_file_id', sa.String(length=256), nullable=True),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('media_type', sa.Enum('VIDEO', 'PHOTO', 'AUDIO', 'DOCUMENT', 'ALBUM', name='mediatype'), nullable=False),
    sa.Column('quality', sa.String(length=20), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('media_info', sa.JSON(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=2048), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media')),
    sa.UniqueConstraint('original_url', 'quality', 'media_type', name='uq_media_url_quality_type')
    )
    op.create_index(op.f('ix_media_media_type'), 'media', ['media_type'], unique=False)
    op.create_index(op.f('ix_media_original_id'), 'media', ['original_id'], unique=False)
    op.create_index(op.f('ix_media_original_url'), 'media', ['original_url'], unique=False)
    op.create_index(op.f('ix_media_quality'), 'media', ['quality'], unique=False)
    op.create_index(op.f('ix_media_source'), 'media', ['source'], unique=False)
    op.create_index(op.f('ix_media_telegram_file_id'), 'media', ['telegram_file_id'], unique=False)
    op.create_table('ad_bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], name=op.f('fk_ad_bots_ad_id_ads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.bot_id'], name=op.f('fk_ad_bots_bot_id_bots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ad_bots'))
    )
    op.create_index(op.f('ix_ad_bots_ad_id'), 'ad_bots', ['ad_id'], unique=False)
    op.create_index(op.f('ix_ad_bots_bot_id'), 'ad_bots', ['bot_id'], unique=False)
    op.create_table('daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('INSTAGRAM', 'TIKTOK', 'YOUTUBE', 'PINTEREST', 'TWITTER', 'REDDIT', 'OTHER', name='mediasource'), nullable=True),
    sa.Column('new_users', sa.Integer(), nullable=False),
    sa.Column('active_users', sa.Integer(), nullable=False),
    sa.Column('downloads', sa.Integer(), nullable=False),
    sa.Column('cached_downloads', sa.Integer(), nullable=False),
    sa.Column('failed_downloads', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name=op.f('fk_daily_stats_bot_id_bots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_stats')),
    sa.UniqueConstraint('date', 'bot_id', 'source', name='uq_daily_stats')
    )
    op.create_index(op.f('ix_daily_stats_bot_id'), 'daily_stats', ['bot_id'], unique=False)
    op.create_index(op.f('ix_daily_stats_date'), 'daily_stats', ['date'], unique=False)
    op.create_index(op.f('ix_daily_stats_source'), 'daily_stats', ['source'], unique=False)
    op.create_table('subscription_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('channel_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_username', sa.String(length=128), nullable=True),
    sa.Column('channel_title', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Enum('REQUIRED', 'OPTIONAL', name='subscriptionstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name=op.f('fk_subscription_channels_bot_id_bots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_channels'))
    )
    op.create_index(op.f('ix_subscription_channels_bot_id'), 'subscription_channels', ['bot_id'], unique=False)
    op.create_table('telegram_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('bot_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('bio', sa.String(length=512), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('total_downloads', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.bot_id'], name=op.f('fk_telegram_users_bot_id_bots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_users'))
    )
    op.create_index(op.f('ix_telegram_users_bot_id'), 'telegram_users', ['bot_id'], unique=False)
    op.create_index(op.f('ix_telegram_users_language'), 'telegram_users', ['language'], unique=False)
    op.create_index(op.f('ix_telegram_users_telegram_id'), 'telegram_users', ['telegram_id'], unique=False)
    op.create_table('ad_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], name=op.f('fk_ad_deliveries_ad_id_ads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.bot_id'], name=op.f('fk_ad_deliveries_bot_id_bots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['telegram_users.id'], name=op.f('fk_ad_deliveries_user_id_telegram_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ad_deliveries'))
    )
    op.create_index(op.f('ix_ad_deliveries_ad_id'), 'ad_deliveries', ['ad_id'], unique=False)
    op.create_index(op.f('ix_ad_deliveries_bot_id'), 'ad_deliveries', ['bot_id'], unique=False)
    op.create_index(op.f('ix_ad_deliveries_user_id'), 'ad_deliveries', ['user_id'], unique=False)
    op.create_table('downloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('original_url', sa.String(length=2048), nullable=False),
    sa.Column('source', sa.Enum('INSTAGRAM', 'TIKTOK', 'YOUTUBE', 'PINTEREST', 'TWITTER', 'REDDIT', 'OTHER', name='mediasource'), nullable=False),
    sa.Column('requested_quality', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'PROCESSING', 'EXTRACTING', 'DOWNLOADING', 'UPLOADING', 'COMPLETED', 'DONE', 'FAILED', 'CACHED', name='downloadstatus'), nullable=False),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name=op.f('fk_downloads_bot_id_bots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_downloads_media_id_media'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['telegram_users.id'], name=op.f('fk_downloads_user_id_telegram_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_downloads'))
    )
    op.create_index(op.f('ix_downloads_bot_id'), 'downloads', ['bot_id'], unique=False)
    op.create_index(op.f('ix_downloads_media_id'), 'downloads', ['media_id'], unique=False)
    op.create_index(op.f('ix_downloads_source'), 'downloads', ['source'], unique=False)
    op.create_index(op.f('ix_downloads_status'), 'downloads', ['status'], unique=False)
    op.create_index(op.f('ix_downloads_user_id'), 'downloads', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_downloads_user_id'), table_name='downloads')
    op.drop_index(op.f('ix_downloads_status'), table_name='downloads')
    op.drop_index(op.f('ix_downloads_source'), table_name='downloads')
    op.drop_index(op.f('ix_downloads_media_id'), table_name='downloads')
    op.drop_index(op.f('ix_downloads_bot_id'), table_name='downloads')
    op.drop_table('downloads')
    op.drop_index(op.f('ix_ad_deliveries_user_id'), table_name='ad_deliveries')
    op.drop_index(op.f('ix_ad_deliveries_bot_id'), table_name='ad_deliveries')
    op.drop_index(op.f('ix_ad_deliveries_ad_id'), table_name='ad_deliveries')
    op.drop_table('ad_deliveries')
    op.drop_index(op.f('ix_telegram_users_telegram_id'), table_name='telegram_users')
    op.drop_index(op.f('ix_telegram_users_language'), table_name='telegram_users')
    op.drop_index(op.f('ix_telegram_users_bot_id'), table_name='telegram_users')
    op.drop_table('telegram_users')
    op.drop_index(op.f('ix_subscription_channels_bot_id'), table_name='subscription_channels')
    op.drop_table('subscription_channels')
    op.drop_index(op.f('ix_daily_stats_source'), table_name='daily_stats')
    op.drop_index(op.f('ix_daily_stats_date'), table_name='daily_stats')
    op.drop_index(op.f('ix_daily_stats_bot_id'), table_name='daily_stats')
    op.drop_table('daily_stats')
    op.drop_index(op.f('ix_ad_bots_bot_id'), table_name='ad_bots')
    op.drop_index(op.f('ix_ad_bots_ad_id'), table_name='ad_bots')
    op.drop_table('ad_bots')
    op.drop_index(op.f('ix_media_telegram_file_id'), table_name='media')
    op.drop_index(op.f('ix_media_source'), table_name='media')
    op.drop_index(op.f('ix_media_quality'), table_name='media')
    op.drop_index(op.f('ix_media_original_url'), table_name='media')
    op.drop_index(op.f('ix_media_original_id'), table_name='media')
    op.drop_index(op.f('ix_media_media_type'), table_name='media')
    op.drop_table('media')
    op.drop_table('cache_channels')
    op.drop_index(op.f('ix_bots_token'), table_name='bots')
    op.drop_index(op.f('ix_bots_bot_id'), table_name='bots')
    op.drop_table('bots')
    op.drop_index(op.f('ix_ads_target_language'), table_name='ads')
    op.drop_index(op.f('ix_ads_expires_at'), table_name='ads')
    op.drop_index(op.f('ix_ads_ad_uuid'), table_name='ads')
    op.drop_table('ads')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
