"""
Скрипт для получения cookies из браузера для yt-dlp.

Использует библиотеку browser_cookie3 для извлечения cookies из браузера.
Поддерживает: Chrome, Firefox, Edge, Safari, Opera.

Установка:
    uv add browser_cookie3

Использование:
    uv run scripts/extract_cookies.py instagram
    uv run scripts/extract_cookies.py youtube
    uv run scripts/extract_cookies.py --all
"""

import sys
from pathlib import Path

import click

# Путь для сохранения cookies
COOKIES_DIR = Path("storage/cookies")
COOKIES_DIR.mkdir(parents=True, exist_ok=True)


def get_cookies_for_platform(platform: str, browser: str = None) -> str:
    """
    Извлекает cookies для указанной платформы из браузера.

    Args:
        platform: instagram, youtube, tiktok, pinterest, vk
        browser: chrome, firefox, edge, safari, opera (по умолчанию chrome)

    Returns:
        Путь к файлу cookies в формате Netscape
    """
    try:
        import browser_cookie3 as bc
    except ImportError:
        print("❌ browser_cookie3 не установлен")
        print("Установите: uv add browser_cookie3")
        sys.exit(1)

    # Маппинг платформ на домены
    platform_domains = {
        "instagram": [".instagram.com"],
        "youtube": [".youtube.com", ".google.com"],
        "tiktok": [".tiktok.com"],
        "pinterest": [".pinterest.com", ".pinterest.ru"],
        "vk": [".vk.com", ".vk.ru"],
        "twitter": [".twitter.com", ".x.com"],
        "facebook": [".facebook.com"],
    }

    if platform not in platform_domains:
        print(f"❌ Неизвестная платформа: {platform}")
        print(f"Доступные: {', '.join(platform_domains.keys())}")
        sys.exit(1)

    domains = platform_domains[platform]

    # Выбираем браузер
    browsers = {
        "chrome": bc.chrome,
        "firefox": bc.firefox,
        "edge": bc.edge,
        "safari": bc.safari,
        "opera": bc.opera,
    }

    if browser and browser not in browsers:
        print(f"❌ Неизвестный браузер: {browser}")
        print(f"Доступные: {', '.join(browsers.keys())}")
        sys.exit(1)

    browser_func = browsers.get(browser, bc.chrome)

    print(f"🔍 Извлекаем cookies для {platform} из {browser or 'Chrome'}...")

    try:
        # Получаем cookies для всех доменов платформы
        all_cookies = []
        for domain in domains:
            try:
                cookies = browser_func(domain_filter=domain)
                all_cookies.extend(cookies)
            except Exception:
                pass

        if not all_cookies:
            print(f"⚠️ Cookies для {platform} не найдены")
            print(f"Убедитесь что вы залогинены в {platform} в браузере")
            return None

        print(f"✅ Найдено {len(all_cookies)} cookies")

        # Сохраняем в формате Netscape (yt-dlp формат)
        output_file = COOKIES_DIR / f"{platform}_cookies.txt"
        _save_netscape_cookies(all_cookies, output_file)

        print(f"💾 Сохранено в: {output_file}")
        return str(output_file)

    except Exception as e:
        print(f"❌ Ошибка при извлечении cookies: {e}")
        return None


def _save_netscape_cookies(cookies, output_file: Path):
    """Сохраняет cookies в формате Netscape (совместимо с yt-dlp)"""
    with open(output_file, "w") as f:
        # Netscape cookie file header
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file is generated by yt-dlp.  Do not edit.\n\n")

        for cookie in cookies:
            try:
                domain = cookie.domain
                # Для доменов начинающихся с точки - убираем точку для совместимости
                if domain.startswith("."):
                    domain = domain[1:]
                    include_subdomains = "TRUE"
                else:
                    include_subdomains = "FALSE"

                path = cookie.path if cookie.path else "/"
                secure = "TRUE" if cookie.secure else "FALSE"
                expires = str(int(cookie.expires.timestamp())) if cookie.expires else "0"
                name = cookie.name
                value = cookie.value

                f.write(f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n")
            except Exception:
                # Пропускаем битые cookies
                pass

    print(f"📝 Формат: Netscape (совместим с yt-dlp)")


@click.command()
@click.argument("platforms", nargs=-1)
@click.option(
    "--browser",
    "-b",
    type=click.Choice(["chrome", "firefox", "edge", "safari", "opera"]),
    default=None,
    help="Браузер из которого извлекать cookies (по умолчанию Chrome)",
)
@click.option(
    "--all",
    "-a",
    is_flag=True,
    help="Извлечь cookies для всех поддерживаемых платформ",
)
def main(platforms, browser, all):
    """Извлечение cookies из браузера для yt-dlp"""

    if all:
        platforms_list = ["instagram", "youtube", "tiktok", "pinterest", "vk"]
    elif platforms:
        platforms_list = list(platforms)
    else:
        print("❌ Укажите платформу или используйте --all")
        print("Пример: uv run scripts/extract_cookies.py instagram")
        print("Пример: uv run scripts/extract_cookies.py --all")
        sys.exit(1)

    print("=" * 60)
    print("🍪 Cookie Extractor for yt-dlp")
    print("=" * 60)
    print()

    success_count = 0
    for platform in platforms_list:
        result = get_cookies_for_platform(platform, browser)
        if result:
            success_count += 1
        print()

    print("=" * 60)
    print(f"✅ Готово! Извлечено cookies для {success_count}/{len(platforms_list)} платформ")
    print()
    print("📁 Файлы сохранены в: storage/cookies/")
    print("⚠️  Важно:")
    print("   - Cookies действуют ~30-90 дней")
    print("   - Обновляйте когда скачивание перестанет работать")
    print("   - Не выходите из аккаунта в браузере")
    print("=" * 60)


if __name__ == "__main__":
    main()
